import { Category, Restaurant, MenuItem, Order, Courier, PlatformMetrics, Reservation, OutingPlan, RestaurantReview } from './types';

export const DAKAR_NEIGHBORHOODS = [
  'Tous les quartiers',
  'Malika',
  'Keur Massar',
  'Yeumbeul',
  'Tivaouane Peulh',
  'Guédiawaye',
  'Pikine',
  'Thiaroye',
  'Mbao',
  'Almadies',
  'Ngor',
  'Yoff',
  'Ouakam',
  'Mermoz',
  'Sacré-Cœur',
  'Point E',
  'Fann Résidence',
  'Plateau',
  'Médina',
  'Grand Dakar',
  'Hann Maristes',
  'Rufisque',
  'Diamniadio',
];


export interface DakarZoneItem {
  id: string;
  name: string;
  shortName: string;
  image: string;
  neighborhood: string;
}

export const DAKAR_ZONES: DakarZoneItem[] = [
  {
    id: 'zone-almadies',
    name: 'Zone Almadies',
    shortName: 'Almadies',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Almadies',
  },
  {
    id: 'zone-plateau',
    name: 'Zone Plateau',
    shortName: 'Plateau',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Plateau',
  },
  {
    id: 'zone-vdn',
    name: 'Zone VDN',
    shortName: 'VDN',
    image: 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Mermoz',
  },
  {
    id: 'zone-pikine',
    name: 'Zone Pikine',
    shortName: 'Pikine',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Pikine',
  },
  {
    id: 'zone-keur-massar',
    name: 'Zone Keur Massar',
    shortName: 'Keur Massar',
    image: 'https://images.unsplash.com/photo-1509749837427-ac94a2553d0e?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Keur Massar',
  },
  {
    id: 'zone-ngor',
    name: 'Zone Ngor Virage',
    shortName: 'Ngor',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=200&q=80',
    neighborhood: 'Ngor',
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-thieb',
    name: 'Thiéboudienne',
    slug: 'thieb',
    icon: '🍲',
    description: 'Le roi de la teranga : Penda Mbaye, Thiéb blanc au poisson frais ou viande',
  },
  {
    id: 'cat-yassa',
    name: 'Yassa & Mafé',
    slug: 'yassa-mafe',
    icon: '🍋',
    description: 'Poulet mariné au citron et oignons confits, sauce arachide onctueuse',
  },
  {
    id: 'cat-dibi',
    name: 'Dibi & Grillades',
    slug: 'dibi',
    icon: '🥩',
    description: 'Agneau rôti au feu de bois façon Dibiterie dakaroise, oignons et piment',
  },
  {
    id: 'cat-poisson',
    name: 'Poissons & Fruits de Mer',
    slug: 'fruits-de-mer',
    icon: '🐟',
    description: 'Thiof braisé, brochettes de lotte, gambas des côtes de Ngor',
  },
  {
    id: 'cat-street',
    name: 'Street Food & Pastels',
    slug: 'street-food',
    icon: '🥟',
    description: 'Pastels dorés croustillants au poisson, Fataya, accras et beignets',
  },
  {
    id: 'cat-boissons',
    name: 'Jus Locaux & Desserts',
    slug: 'boissons-desserts',
    icon: '🍹',
    description: 'Bissap frais à la menthe, Bouye onctueux, Ditakh et Thiakry au yaourt doux',
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'resto-1',
    name: 'Le Thiéb Royal de Dakar',
    tagline: 'L’authenticité du Thiéboudienne rouge & blanc cuit au feu de bois',
    description: 'Maison réputée pour ses recettes ancestrales de Saint-Louis et Dakar, avec Thiof frais du jour, légumes mijotés et riz parfumé.',
    coverImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Almadies',
    address: 'Route des Almadies, en face de la pointe des Almadies, Dakar',
    coordinates: { lat: 14.7431, lng: -17.5186 },
    priceRange: '2500 - 6000 FCFA',
    ambianceTags: ['Vue Océan', 'Romantique', 'Sortie Couple', 'Terrasse Almadies', 'Teranga Chic'],
    amenities: ['Terrasse vue mer', 'Climatisation', 'Parking privé gardé', 'Wifi gratuit', 'Service Voiturier'],
    openingHours: {
      'Lundi - Vendredi': '11h30 - 23h30',
      'Samedi - Dimanche': '11h00 - 01h00'
    },
    deliveryTimeEstimate: '25-35 min',
    deliveryFee: 1500,
    minOrder: 3000,
    isOpen: true,
    featuredTags: ['Thiéb Spécial', 'Cuisine Teranga', 'Best Seller Dakar'],
    ownerName: 'Chef Partenaire',
    phone: '+221 77 000 00 00',
    whatsapp: '+221770000000',
    instagram: '@thiebroyaldakar',
  },
  {
    id: 'resto-2',
    name: 'Dibiterie Centrale du Plateau',
    tagline: 'L’agneau tendre braisé à l’ancienne et sauce moutarde pimentée',
    description: 'La véritable Dibiterie sénégalaise : découpe à la minute, cuisson au charbon de bois, servie avec oignons croquants et piment vert.',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Plateau',
    address: 'Avenue Pompidou x Rue Vincens, Dakar Plateau',
    coordinates: { lat: 14.6710, lng: -17.4320 },
    priceRange: '2500 - 6000 FCFA',
    ambianceTags: ['Dibi Braisé', 'Sortie Entre Amis', 'Ambiance Nocturne', 'Au Cœur de Dakar'],
    amenities: ['Espace Grillades', 'Climatisation', 'Salle VIP', 'Emporter & Sur Place'],
    openingHours: {
      'Lundi - Dimanche': '12h00 - 02h00 (Nocturne)'
    },
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 4000,
    isOpen: true,
    featuredTags: ['Dibi Chaud', 'Viande Fraîche', 'Nocturne'],
    ownerName: 'Chef Partenaire',
    phone: '+221 78 000 00 00',
    whatsapp: '+221780000000',
  },
  {
    id: 'resto-3',
    name: 'Chez Coumba Teranga',
    tagline: 'Yassa Poulet braisé, Mafé onctueux et Pastels dorés faits maison',
    description: 'Une cuisine généreuse comme à la maison. Nos sauces Yassa sont mijotées pendant 3 heures pour un fondant incomparable.',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Mermoz',
    address: 'Mermoz Pyrotechnie, près de la VDN, Dakar',
    coordinates: { lat: 14.7080, lng: -17.4720 },
    priceRange: '1000 - 3000 FCFA',
    ambianceTags: ['Familial', 'Convivial', 'Cuisine Maison', 'Sortie Déjeuner'],
    amenities: ['Terrasse Ombragée', 'Wifi Gratuit', 'Parking facile'],
    openingHours: {
      'Lundi - Samedi': '11h00 - 22h30'
    },
    deliveryTimeEstimate: '30-40 min',
    deliveryFee: 1200,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Yassa Poulet', 'Mafé Boeuf', 'Pastels'],
    ownerName: 'Chef Partenaire',
    phone: '+221 76 000 00 00',
    whatsapp: '+221760000000',
  },
  {
    id: 'resto-kamiss',
    name: 'Chez Kamiss',
    tagline: 'Le spot incontournable de Ngor Virage • Grillades, Thiéb & Spécialités d’exception',
    description: 'Une atmosphère chaleureuse au bord de l’océan à Ngor Virage, offrant les meilleurs Thiéboudienne, burgers gourmets, grillades et fritures de poissons frais.',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Ngor',
    address: 'Ngor Virage, Corniche Ouest face à l\'île de Ngor, Dakar',
    coordinates: { lat: 14.7550, lng: -17.5140 },
    priceRange: '2500 - 6000 FCFA',
    ambianceTags: ['Coucher de Soleil', 'Sortie Romantique', 'Vue Océan Ngor', 'Terrasse Lounge', 'Tendance Dakar'],
    amenities: ['Terrasse panoramique', 'Coucher de soleil garanti', 'Cocktails sans alcool & mocktails', 'Wifi fibre', 'Parking surveillé'],
    openingHours: {
      'Tous les jours': '11h00 - 00h30'
    },
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Ngor Virage', 'Thiéb Royal', 'Burgers & Poissons', 'Top Resto'],
    ownerName: 'Chef Partenaire',
    phone: '+221 77 000 00 00',
    whatsapp: '+221770000000',
    instagram: '@chezkamiss_dakar',
  },
  {
    id: 'resto-4',
    name: 'L’Océan de Ngor',
    tagline: 'Thiof braisé géant, Gambas grillées et langoustes fraîches',
    description: 'Directement débarqués des pirogues de Ngor et Yoff, nos poissons et crustacés sont marinés aux herbes locales et grillés avec précision.',
    coverImage: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Ngor',
    address: 'Corniche des Almadies x Plage de Ngor',
    coordinates: { lat: 14.7570, lng: -17.5180 },
    priceRange: '5000 - 15000 FCFA',
    ambianceTags: ['Pieds dans l\'eau', 'Poissons Frais', 'Fruits de Mer', 'Sortie Romantique'],
    amenities: ['Plage privée', 'Terrasse pieds dans l\'eau', 'Espace Dégustation'],
    openingHours: {
      'Mardi - Dimanche': '12h00 - 23h00'
    },
    deliveryTimeEstimate: '35-45 min',
    deliveryFee: 2000,
    minOrder: 5000,
    isOpen: true,
    featuredTags: ['Thiof Braisé', 'Fruits de Mer', 'Vue Océan'],
    ownerName: 'Chef Partenaire',
    phone: '+221 77 000 00 00',
    whatsapp: '+221770000000',
  },
  {
    id: 'resto-yoff-1',
    name: 'Délices & Thiéb de Yoff Plage',
    tagline: 'Le vrai Thiéb blanc au poisson frais & Dibi chaud face à l’océan de Yoff',
    description: 'Institution traditionnelle de Yoff Tonghor, réputée pour ses poissons braisés débarqués du quai et son Thiéb Penda Mbaye mijoté au feu de bois.',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Yoff',
    address: 'Plage de Yoff BCEAO, près du Quai de Pêche, Dakar',
    coordinates: { lat: 14.7610, lng: -17.4680 },
    priceRange: '2500 - 6000 FCFA',
    ambianceTags: ['Bord de Mer Yoff', 'Cuisine Pêcheur', 'Dibi Chaud', 'Authentique Dakar'],
    amenities: ['Terrasse Plage Yoff', 'Parking gratuit', 'Vue directe sur le large'],
    openingHours: {
      'Lundi - Dimanche': '11h30 - 23h00'
    },
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Yoff Plage', 'Thiéb Blanc', 'Poisson Braisé', 'Spécial Quai'],
    ownerName: 'Chef Partenaire',
    phone: '+221 77 000 00 00',
    whatsapp: '+221770000000',
  },
  {
    id: 'resto-ouakam-1',
    name: 'Le Teranga Ouakam & Grillades',
    tagline: 'Poulet Yassa braisé croustillant, Pastels dorés et Dibi savoureux',
    description: 'Au pied du Monument de la Renaissance à Ouakam, nous vous servons les meilleures grillades et plats mijotés de la capitale.',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Ouakam',
    address: 'Cité Assemblée, Route du Monument de la Renaissance, Ouakam',
    coordinates: { lat: 14.7210, lng: -17.4950 },
    priceRange: '2500 - 6000 FCFA',
    ambianceTags: ['Vue Monument Renaissance', 'Grillades & Yassa', 'Sortie Familiale'],
    amenities: ['Terrasse panoramique', 'Wifi gratuit', 'Parking surveillé'],
    openingHours: {
      'Lundi - Dimanche': '12h00 - 23h30'
    },
    deliveryTimeEstimate: '25-35 min',
    deliveryFee: 1200,
    minOrder: 3000,
    isOpen: true,
    featuredTags: ['Ouakam Monument', 'Yassa Braisé', 'Pastels Dorés'],
    ownerName: 'Chef Partenaire',
    phone: '+221 78 000 00 00',
    whatsapp: '+221780000000',
  },
  {
    id: 'resto-malika',
    name: 'Le Délice des Niayes & Grillades de Malika',
    tagline: 'L’authenticité de Malika Plage : Thiof frais des Niayes, Dibi d’agneau & Thiéb Penda Mbaye',
    description: 'Au cœur de Malika près des Niayes et du littoral Nord, notre chef prépare des poissons braisés ultra-frais, des grillades au feu de bois et des jus locaux bio.',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Malika',
    address: 'Route de Malika Plage, près du Centre de Santé, Malika, Dakar',
    coordinates: { lat: 14.7925, lng: -17.3365 },
    priceRange: '2000 - 5000 FCFA',
    ambianceTags: ['Malika Plage', 'Fraîcheur des Niayes', 'Dibi Chaud', 'Familial'],
    amenities: ['Terrasse aérée', 'Parking gratuit', 'Livraison express Malika & Keur Massar'],
    openingHours: {
      'Lundi - Dimanche': '11h00 - 23h30'
    },
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Spécial Malika', 'Poisson des Niayes', 'Dibi Frais'],
    ownerName: 'Chef Partenaire',
    phone: '+221 77 000 00 00',
    whatsapp: '+221770000000',
    instagram: '@delices_malika',
  },
  {
    id: 'resto-pikine',
    name: 'Dibiterie & Teranga de Pikine Icotaf',
    tagline: 'Le grand Dibi réputé de Pikine & Thiéboudienne traditionnel',
    description: 'Une véritable institution de la banlieue dakaroise : agneau braisé selon la tradition, oignons caramélisés au piment et jus de Bouye frais.',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    ],
    logo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    reviewCount: 0,
    reviews: [],
    neighborhood: 'Pikine',
    address: 'Tally Boubess x Icotaf, Pikine, Dakar',
    coordinates: { lat: 14.7570, lng: -17.3940 },
    priceRange: '2000 - 5500 FCFA',
    ambianceTags: ['Dibi Traditionnel', 'Pikine Icotaf', 'Convivial', 'Nocturne'],
    amenities: ['Espace Grillades', 'Emporter & Livraison', 'Paiement Wave direct'],
    openingHours: {
      'Tous les jours': '12h00 - 01h00'
    },
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Dibi Pikine', 'Tally Boubess', 'Grillades'],
    ownerName: 'Chef Partenaire',
    phone: '+221 76 000 00 00',
    whatsapp: '+221760000000',
  },

];


export const INITIAL_RESERVATIONS: Reservation[] = [];

export const INITIAL_OUTING_PLANS: OutingPlan[] = [];


export const MENU_ITEMS: MenuItem[] = [
  // Plats Phares Thiob Express Dakar
  {
    id: 'menu-thieb-jeun',
    restaurantId: 'resto-kamiss',
    name: 'Thiébou jeun',
    description: 'Le plat national par excellence : riz rouge savoureux, darne de poisson frais grillé, légumes mijotés, nététou et beugueudj.',
    price: 3500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Thiéb Royal', 'Poisson Frais', 'Dakar Express'],
  },
  {
    id: 'menu-burger-royal',
    restaurantId: 'resto-kamiss',
    name: 'Burger royal',
    description: 'Double steak haché pur bœuf mariné, double cheddar fondant, cornichons craquants, laitue fraîche et sauce secrète maison.',
    price: 2500,
    category: 'cat-street',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 15,
    tags: ['Burger Double', 'Cheddar Fondant', 'Gourmet'],
  },
  {
    id: 'menu-friture-poisson',
    restaurantId: 'resto-kamiss',
    name: 'Friture de poisson',
    description: 'Assiette de poissons de roche et crevettes croustillantes dorées aux épices douces, servie avec frites dorées, rondelles de tomates et sauce piment.',
    price: 2500,
    category: 'cat-poisson',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Friture Mer', 'Crevettes & Poissons', 'Croustillant'],
  },
  // Plats de Yoff (resto-yoff-1)
  {
    id: 'menu-yoff-thieb-blanc',
    restaurantId: 'resto-yoff-1',
    name: 'Thiébou Jën Blanc de Yoff Tonghor',
    description: 'Le célèbre Thiéb blanc de Yoff au poisson Thiof frais du quai, riz parfumé aux oignons dorés, piment vert et sauce tamarin beugueudj.',
    price: 3500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Yoff Plage', 'Thiéb Blanc', 'Thiof Quai'],
  },
  {
    id: 'menu-yoff-dibi',
    restaurantId: 'resto-yoff-1',
    name: 'Dibi Agneau Braisé de Yoff',
    description: 'Viande d’agneau braisée au charbon de bois, servie avec oignons doux confits, moutarde forte de Dijon et piment dakarois.',
    price: 4500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 15,
    tags: ['Dibi Chaud', 'Agneau Frais', 'Yoff'],
  },
  // Plats de Ouakam (resto-ouakam-1)
  {
    id: 'menu-ouakam-yassa',
    restaurantId: 'resto-ouakam-1',
    name: 'Yassa Poulet Braisé Ouakam',
    description: 'Cuisse de poulet fermier braisée au feu vif, fondue d’oignons au citron vert et moutarde, accompagnée de riz blanc brisé.',
    price: 3000,
    category: 'cat-yassa',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Ouakam', 'Yassa Citron', 'Poulet Braisé'],
  },
  // Plats du resto-1 (Le Thiéb Royal)
  {
    id: 'menu-1',
    restaurantId: 'resto-1',
    name: 'Ceebu Jën Rouge Royal (Thiéboudienne)',
    description: 'Riz rouge cuit au bouillon de poisson parfumé, tranche généreuse de Thiof braisé, carotte, chou, manioc, beugueudj et nététou.',
    price: 4500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Plat National', 'Thiof Frais', 'Piment Doux'],
  },
  {
    id: 'menu-2',
    restaurantId: 'resto-1',
    name: 'Ceebu Jën Blanc (Thiéb Blanc Saint-Louisien)',
    description: 'Riz blanc délicatement mijoté, Thiof doré, sauce feuille verte aux épices (Beugueudj), tamarin acidulé et légumes fondants.',
    price: 4500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Saint-Louis', 'Sauce Tamarin', 'Beugueudj'],
  },
  {
    id: 'menu-3',
    restaurantId: 'resto-1',
    name: 'Ceebu Yapp (Thiéb à la Viande Tendre)',
    description: 'Riz doré aux petits légumes et morceaux de viande de bœuf caramélisés, raisins secs, servi avec piment et sauce moutarde.',
    price: 4000,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  // Plats du resto-2 (Dibiterie Centrale)
  {
    id: 'menu-4',
    restaurantId: 'resto-2',
    name: 'Portion Dibi d’Agneau Braisé (500g)',
    description: 'Morceaux choisis d’agneau grillés à la flamme vive, assaisonnés au secret du chef, servis avec oignons émincés et piment.',
    price: 5500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 25,
    tags: ['Charbon de bois', 'Spécialité Dakar', '500g'],
  },
  {
    id: 'menu-5',
    restaurantId: 'resto-2',
    name: 'Brochettes de Filet de Bœuf (4 pièces)',
    description: 'Brochettes marinées aux épices douces, poivrons verts et oignons braisés, accompagnées d’alloco ou frites maison.',
    price: 3500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  // Plats du resto-3 (Chez Coumba)
  {
    id: 'menu-6',
    restaurantId: 'resto-3',
    name: 'Yassa Poulet Braisé Fermier',
    description: 'Cuisse et suprême de poulet braisés puis mijotés dans une compotée d’oignons citronnés, olives vertes et moutarde de Dijon.',
    price: 3800,
    category: 'cat-yassa',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 18,
    tags: ['Citron Vert', 'Poulet Braisé', 'Riz Blanc'],
  },
  {
    id: 'menu-7',
    restaurantId: 'resto-3',
    name: 'Mafé Bœuf Crémeux',
    description: 'Mijoté de bœuf tendre dans une sauce onctueuse à la pâte d’arachide pure, carottes et patates douces, servi avec riz blanc.',
    price: 3800,
    category: 'cat-yassa',
    image: 'https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 18,
  },
  {
    id: 'menu-8',
    restaurantId: 'resto-3',
    name: 'Portion de 10 Pastels au Thon & Sauce Pimentée',
    description: 'Petits chaussons dorés et croustillants farcis au thon frais épicé, servis avec la fameuse sauce tomate-oignons piquante.',
    price: 2000,
    category: 'cat-street',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 10,
    tags: ['Croustillant', 'Fait Maison', 'Sauce Piquante'],
  },
  // Plats Spécifiques Malika
  {
    id: 'menu-malika-1',
    restaurantId: 'resto-malika',
    name: 'Thiébou Jën des Niayes (Malika)',
    description: 'Riz rouge cuisiné au feu de bois avec Thiof frais de Malika Plage, légumes du jardin des Niayes et nététou traditionnel.',
    price: 3500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Spécial Malika', 'Poisson Frais', 'Best Seller'],
  },
  {
    id: 'menu-malika-2',
    restaurantId: 'resto-malika',
    name: 'Dibi d’Agneau Rôti de Malika (500g)',
    description: 'Morceaux choisis d’agneau braisés aux braises ardentes, accompagnés d’oignons marinés et piment vert.',
    price: 4500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 25,
    tags: ['Dibi Braisé', 'Agneau Frais', 'Malika'],
  },
  // Plats Spécifiques Pikine
  {
    id: 'menu-pikine-1',
    restaurantId: 'resto-pikine',
    name: 'Grand Dibi Chaud de Pikine Icotaf (1kg)',
    description: 'La recette mythique de Pikine : découpe d’agneau tendre, sauce moutarde maison pimentée et oignons doux.',
    price: 6500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Dibi Icotaf', 'Pikine', 'Best Seller'],
  },
  {
    id: 'menu-pikine-2',
    restaurantId: 'resto-pikine',
    name: 'Pastels de Poisson Dorés (15 pcs)',
    description: 'Pastels croustillants garnis de farce généreuse au poisson frais et sauce tomate piquante de Pikine.',
    price: 1500,
    category: 'cat-street',
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 10,
    tags: ['Street Food', 'Pastels Dorés'],
  },
  // Boissons & Desserts partagés
  {
    id: 'menu-9',
    restaurantId: 'resto-1',
    name: 'Jus de Bissap Maison (50cl)',
    description: 'Infusion fraîche de fleurs d’hibiscus du Sénégal avec feuilles de menthe fraîche et touche de fleur d’oranger.',
    price: 1000,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 5,
  },
  {
    id: 'menu-10',
    restaurantId: 'resto-1',
    name: 'Jus de Bouye Onctueux (Pain de Singe 50cl)',
    description: 'Jus velouté et gourmand à base de pulpe de fruit de baobab naturel, vanille et lait doux.',
    price: 1200,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 5,
  },
  {
    id: 'menu-11',
    restaurantId: 'resto-3',
    name: 'Thiakry / Dégué Onctueux',
    description: 'Couscous de mil cuit à la vapeur mélangé à un yaourt battu vanillé, noix de muscade, raisins secs et crème douce.',
    price: 1500,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 5,
  },
];


export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_COURIERS: Courier[] = [];

export const INITIAL_METRICS: PlatformMetrics = {
  totalRevenueGmv: 0,
  platformCommissionEarned: 0,
  totalOrdersToday: 0,
  activeRestaurantsCount: 4,
  activeCouriersCount: 0,
  satisfactionRate: 100,
};


