import { Category, Restaurant, MenuItem, Order, Courier, PlatformMetrics } from './types';

export const DAKAR_NEIGHBORHOODS = [
  'Tous les quartiers',
  'Almadies',
  'Ngor',
  'Plateau',
  'Mermoz',
  'Fann Résidence',
  'Point E',
  'Ouakam',
  'Sacré-Cœur',
  'Yoff',
  'Mamelles',
  'Hann Maristes',
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-thieb',
    name: 'Thiéboudienne',
    slug: 'thieb',
    icon: '🍲',
    description: 'Le roi de la teranga : Penda Mbaye, Thiéb blanc au poisson frais ou viande',
  },
  {
    id: 'cat-yassa',
    name: 'Yassa & Mafé',
    slug: 'yassa-mafe',
    icon: '🍋',
    description: 'Poulet mariné au citron et oignons confits, sauce arachide onctueuse',
  },
  {
    id: 'cat-dibi',
    name: 'Dibi & Grillades',
    slug: 'dibi',
    icon: '🥩',
    description: 'Agneau rôti au feu de bois façon Dibiterie dakaroise, oignons et piment',
  },
  {
    id: 'cat-poisson',
    name: 'Poissons & Fruits de Mer',
    slug: 'fruits-de-mer',
    icon: '🐟',
    description: 'Thiof braisé, brochettes de lotte, gambas des côtes de Ngor',
  },
  {
    id: 'cat-street',
    name: 'Street Food & Pastels',
    slug: 'street-food',
    icon: '🥟',
    description: 'Pastels dorés croustillants au poisson, Fataya, accras et beignets',
  },
  {
    id: 'cat-boissons',
    name: 'Jus Locaux & Desserts',
    slug: 'boissons-desserts',
    icon: '🍹',
    description: 'Bissap frais à la menthe, Bouye onctueux, Ditakh et Thiakry au yaourt doux',
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'resto-1',
    name: 'Le Thiéb Royal de Dakar',
    tagline: 'L’authenticité du Thiéboudienne rouge & blanc cuit au feu de bois',
    description: 'Maison réputée pour ses recettes ancestrales de Saint-Louis et Dakar, avec Thiof frais du jour, légumes mijotés et riz parfumé.',
    coverImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
    rating: 4.9,
    reviewCount: 342,
    neighborhood: 'Almadies',
    address: 'Route des Almadies, en face de la pointe des Almadies, Dakar',
    deliveryTimeEstimate: '25-35 min',
    deliveryFee: 1500,
    minOrder: 3000,
    isOpen: true,
    featuredTags: ['Thiéb Spécial', 'Cuisine Teranga', 'Best Seller Dakar'],
    ownerName: 'Mme Fatou Ndiaye',
    phone: '+221 77 450 12 34',
  },
  {
    id: 'resto-2',
    name: 'Dibiterie Centrale du Plateau',
    tagline: 'L’agneau tendre braisé à l’ancienne et sauce moutarde pimentée',
    description: 'La véritable Dibiterie sénégalaise : découpe à la minute, cuisson au charbon de bois, servie avec oignons croquants et piment vert.',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    logo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=200&q=80',
    rating: 4.8,
    reviewCount: 215,
    neighborhood: 'Plateau',
    address: 'Avenue Pompidou x Rue Vincens, Dakar Plateau',
    deliveryTimeEstimate: '20-30 min',
    deliveryFee: 1000,
    minOrder: 4000,
    isOpen: true,
    featuredTags: ['Dibi Chaud', 'Viande Fraîche', 'Nocturne'],
    ownerName: 'Ousmane Sow',
    phone: '+221 78 220 98 76',
  },
  {
    id: 'resto-3',
    name: 'Chez Coumba Teranga',
    tagline: 'Yassa Poulet braisé, Mafé onctueux et Pastels dorés faits maison',
    description: 'Une cuisine généreuse comme à la maison. Nos sauces Yassa sont mijotées pendant 3 heures pour un fondant incomparable.',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    logo: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=200&q=80',
    rating: 4.7,
    reviewCount: 189,
    neighborhood: 'Mermoz',
    address: 'Mermoz Pyrotechnie, près de la VDN, Dakar',
    deliveryTimeEstimate: '30-40 min',
    deliveryFee: 1200,
    minOrder: 2500,
    isOpen: true,
    featuredTags: ['Yassa Poulet', 'Mafé Boeuf', 'Pastels'],
    ownerName: 'Coumba Ba',
    phone: '+221 76 890 45 12',
  },
  {
    id: 'resto-4',
    name: 'L’Océan de Ngor',
    tagline: 'Thiof braisé géant, Gambas grillées et langoustes fraîches',
    description: 'Directement débarqués des pirogues de Ngor et Yoff, nos poissons et crustacés sont marinés aux herbes locales et grillés avec précision.',
    coverImage: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80',
    logo: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=200&q=80',
    rating: 4.9,
    reviewCount: 410,
    neighborhood: 'Ngor',
    address: 'Corniche des Almadies x Plage de Ngor',
    deliveryTimeEstimate: '35-45 min',
    deliveryFee: 2000,
    minOrder: 5000,
    isOpen: true,
    featuredTags: ['Thiof Braisé', 'Fruits de Mer', 'Vue Océan'],
    ownerName: 'Capitaine Babacar',
    phone: '+221 77 123 78 90',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // Plats du resto-1 (Le Thiéb Royal)
  {
    id: 'menu-1',
    restaurantId: 'resto-1',
    name: 'Ceebu Jën Rouge Royal (Thiéboudienne)',
    description: 'Riz rouge cuit au bouillon de poisson parfumé, tranche généreuse de Thiof braisé, carotte, chou, manioc, beugueudj et nététou.',
    price: 4500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Plat National', 'Thiof Frais', 'Piment Doux'],
  },
  {
    id: 'menu-2',
    restaurantId: 'resto-1',
    name: 'Ceebu Jën Blanc (Thiéb Blanc Saint-Louisien)',
    description: 'Riz blanc délicatement mijoté, Thiof doré, sauce feuille verte aux épices (Beugueudj), tamarin acidulé et légumes fondants.',
    price: 4500,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 20,
    tags: ['Saint-Louis', 'Sauce Tamarin', 'Beugueudj'],
  },
  {
    id: 'menu-3',
    restaurantId: 'resto-1',
    name: 'Ceebu Yapp (Thiéb à la Viande Tendre)',
    description: 'Riz doré aux petits légumes et morceaux de viande de bœuf caramélisés, raisins secs, servi avec piment et sauce moutarde.',
    price: 4000,
    category: 'cat-thieb',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  // Plats du resto-2 (Dibiterie Centrale)
  {
    id: 'menu-4',
    restaurantId: 'resto-2',
    name: 'Portion Dibi d’Agneau Braisé (500g)',
    description: 'Morceaux choisis d’agneau grillés à la flamme vive, assaisonnés au secret du chef, servis avec oignons émincés et piment.',
    price: 5500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 25,
    tags: ['Charbon de bois', 'Spécialité Dakar', '500g'],
  },
  {
    id: 'menu-5',
    restaurantId: 'resto-2',
    name: 'Brochettes de Filet de Bœuf (4 pièces)',
    description: 'Brochettes marinées aux épices douces, poivrons verts et oignons braisés, accompagnées d’alloco ou frites maison.',
    price: 3500,
    category: 'cat-dibi',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  // Plats du resto-3 (Chez Coumba)
  {
    id: 'menu-6',
    restaurantId: 'resto-3',
    name: 'Yassa Poulet Braisé Fermier',
    description: 'Cuisse et suprême de poulet braisés puis mijotés dans une compotée d’oignons citronnés, olives vertes et moutarde de Dijon.',
    price: 3800,
    category: 'cat-yassa',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 18,
    tags: ['Citron Vert', 'Poulet Braisé', 'Riz Blanc'],
  },
  {
    id: 'menu-7',
    restaurantId: 'resto-3',
    name: 'Mafé Bœuf Crémeux',
    description: 'Mijoté de bœuf tendre dans une sauce onctueuse à la pâte d’arachide pure, carottes et patates douces, servi avec riz blanc.',
    price: 3800,
    category: 'cat-yassa',
    image: 'https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 18,
  },
  {
    id: 'menu-8',
    restaurantId: 'resto-3',
    name: 'Portion de 10 Pastels au Thon & Sauce Pimentée',
    description: 'Petits chaussons dorés et croustillants farcis au thon frais épicé, servis avec la fameuse sauce tomate-oignons piquante.',
    price: 2000,
    category: 'cat-street',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 10,
    tags: ['Croustillant', 'Fait Maison', 'Sauce Piquante'],
  },
  // Boissons & Desserts partagés
  {
    id: 'menu-9',
    restaurantId: 'resto-1',
    name: 'Jus de Bissap Maison (50cl)',
    description: 'Infusion fraîche de fleurs d’hibiscus du Sénégal avec feuilles de menthe fraîche et touche de fleur d’oranger.',
    price: 1000,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    preparationTimeMinutes: 5,
  },
  {
    id: 'menu-10',
    restaurantId: 'resto-1',
    name: 'Jus de Bouye Onctueux (Pain de Singe 50cl)',
    description: 'Jus velouté et gourmand à base de pulpe de fruit de baobab naturel, vanille et lait doux.',
    price: 1200,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 5,
  },
  {
    id: 'menu-11',
    restaurantId: 'resto-3',
    name: 'Thiakry / Dégué Onctueux',
    description: 'Couscous de mil cuit à la vapeur mélangé à un yaourt battu vanillé, noix de muscade, raisins secs et crème douce.',
    price: 1500,
    category: 'cat-boissons',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isPopular: true,
    preparationTimeMinutes: 5,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'DKR-8942',
    createdAt: 'Il y a 8 min',
    clientId: 'user-client-1',
    clientName: 'Moussa Diop',
    clientPhone: '+221 77 654 32 10',
    restaurantId: 'resto-1',
    restaurantName: 'Le Thiéb Royal de Dakar',
    courierId: 'cour-1',
    courierName: 'Ibrahima Fall (Moto Jakarta)',
    courierPhone: '+221 70 812 34 56',
    status: 'in_transit',
    items: [
      { menuItemId: 'menu-1', name: 'Ceebu Jën Rouge Royal', price: 4500, quantity: 2, notes: 'Bien pimenté svp' },
      { menuItemId: 'menu-9', name: 'Jus de Bissap Maison', price: 1000, quantity: 2 },
    ],
    subtotal: 11000,
    deliveryFee: 1500,
    platformFee: 500,
    total: 13000,
    paymentMethod: 'wave',
    paymentStatus: 'paid',
    deliveryAddress: {
      neighborhood: 'Almadies',
      street: 'Rue du Jardin x Route des Almadies',
      details: 'Villa N° 45, portail vert',
    },
    estimatedDeliveryTime: '12 min',
  },
  {
    id: 'ord-102',
    orderNumber: 'DKR-8943',
    createdAt: 'Il y a 14 min',
    clientId: 'user-client-2',
    clientName: 'Aïssatou Sow',
    clientPhone: '+221 78 111 22 33',
    restaurantId: 'resto-1',
    restaurantName: 'Le Thiéb Royal de Dakar',
    status: 'preparing',
    items: [
      { menuItemId: 'menu-2', name: 'Ceebu Jën Blanc', price: 4500, quantity: 1 },
      { menuItemId: 'menu-10', name: 'Jus de Bouye Onctueux', price: 1200, quantity: 1 },
    ],
    subtotal: 5700,
    deliveryFee: 1500,
    platformFee: 500,
    total: 7700,
    paymentMethod: 'orange_money',
    paymentStatus: 'paid',
    deliveryAddress: {
      neighborhood: 'Mermoz',
      street: 'Avenue Cheikh Anta Diop',
      details: 'Immeuble Horizon, 3ème étage',
    },
    estimatedDeliveryTime: '25 min',
  },
  {
    id: 'ord-103',
    orderNumber: 'DKR-8944',
    createdAt: 'Il y a 2 min',
    clientId: 'user-client-3',
    clientName: 'Cheikh Ndao',
    clientPhone: '+221 76 333 44 55',
    restaurantId: 'resto-1',
    restaurantName: 'Le Thiéb Royal de Dakar',
    status: 'pending',
    items: [
      { menuItemId: 'menu-3', name: 'Ceebu Yapp', price: 4000, quantity: 3 },
      { menuItemId: 'menu-11', name: 'Thiakry / Dégué Onctueux', price: 1500, quantity: 3 },
    ],
    subtotal: 16500,
    deliveryFee: 1500,
    platformFee: 700,
    total: 18700,
    paymentMethod: 'wave',
    paymentStatus: 'paid',
    deliveryAddress: {
      neighborhood: 'Plateau',
      street: 'Boulevard de la République',
      details: 'Bureau 402',
    },
    estimatedDeliveryTime: '35 min',
  },
];

export const INITIAL_COURIERS: Courier[] = [
  {
    id: 'cour-1',
    name: 'Ibrahima Fall',
    phone: '+221 70 812 34 56',
    vehicleType: 'moto',
    plateNumber: 'DK-4921-AZ',
    isOnline: true,
    currentNeighborhood: 'Almadies',
    rating: 4.95,
    completedDeliveries: 148,
    todayEarnings: 18500,
    activeOrderId: 'ord-101',
  },
  {
    id: 'cour-2',
    name: 'Modou Diouf',
    phone: '+221 77 987 65 43',
    vehicleType: 'scooter',
    plateNumber: 'DK-1082-BC',
    isOnline: true,
    currentNeighborhood: 'Plateau',
    rating: 4.88,
    completedDeliveries: 94,
    todayEarnings: 12000,
  },
  {
    id: 'cour-3',
    name: 'Amadou Seck',
    phone: '+221 78 444 55 66',
    vehicleType: 'moto',
    plateNumber: 'DK-7733-XY',
    isOnline: false,
    currentNeighborhood: 'Yoff',
    rating: 4.75,
    completedDeliveries: 210,
    todayEarnings: 0,
  },
];

export const INITIAL_METRICS: PlatformMetrics = {
  totalRevenueGmv: 4850000, // FCFA
  platformCommissionEarned: 679000, // FCFA (~14%)
  totalOrdersToday: 384,
  activeRestaurantsCount: 42,
  activeCouriersCount: 28,
  satisfactionRate: 98.4,
};
